version: '2'
services:
  mysql-openstack:
    image: mysql:5.5
    container_name: mysql-openstack
    hostname: mysql-openstack
    environment:
    - MYSQL_ROOT_PASSWORD=mysql123

  keystone-server:
    build: docker/keystone/.
#    image: ttsubo/keystone:queens
#    command: /bin/sh -c "sleep 20; /root/init_queens.sh; /root/start_keystone.sh"
    image: ttsubo/keystone:mitaka
    command: /bin/sh -c "sleep 20; /root/init_mitaka.sh; /root/start_keystone.sh"
    container_name: keystone-server
    hostname: keystone-server
    volumes:
    - ./log:/log
    environment:
    - OS_TOKEN=ADMIN
    - OS_URL=http://localhost:35357/v3
    - OS_IDENTITY_API_VERSION=3 

  glance-server:
    build: docker/glance/.
    image: ttsubo/glance:queens
    command: /bin/sh -c "sleep 60; /root/init_queens.sh; /usr/bin/supervisord -n"
    container_name: glance-server
    hostname: glance-server
    volumes:
    - ./log:/log
    environment:
    - OS_PROJECT_DOMAIN_NAME=default
    - OS_USER_DOMAIN_NAME=default
    - OS_PROJECT_NAME=admin
    - OS_USERNAME=admin
    - OS_PASSWORD=passw0rd
    - OS_AUTH_URL=http://keystone-server:35357/v3
    - OS_IDENTITY_API_VERSION=3
    - OS_IMAGE_API_VERSION=2

  nova-server:
    build: docker/nova/.
    image: ttsubo/nova:queens
    command: /bin/sh -c "sleep 80; /root/init_queens.sh; /usr/bin/supervisord -n"
    container_name: nova-server
    hostname: nova-server
    volumes:
    - ./log:/log
    environment:
    - OS_PROJECT_DOMAIN_NAME=default
    - OS_USER_DOMAIN_NAME=default
    - OS_PROJECT_NAME=admin
    - OS_USERNAME=admin
    - OS_PASSWORD=passw0rd
    - OS_AUTH_URL=http://keystone-server:35357/v3
    - OS_IDENTITY_API_VERSION=3
    - OS_IMAGE_API_VERSION=2
    privileged: true

  neutron-server:
    build: docker/neutron/.
    image: ttsubo/neutron:queens
    command: /bin/sh -c "sleep 80; /root/init_queens.sh; /usr/bin/supervisord -n"
    container_name: neutron-server
    hostname: neutron-server
    volumes:
    - ./log:/log
    environment:
    - OS_PROJECT_DOMAIN_NAME=default
    - OS_USER_DOMAIN_NAME=default
    - OS_PROJECT_NAME=admin
    - OS_USERNAME=admin
    - OS_PASSWORD=passw0rd
    - OS_AUTH_URL=http://keystone-server:35357/v3
    - OS_IDENTITY_API_VERSION=3
    - OS_IMAGE_API_VERSION=2
    privileged: true

  heat-server:
    build: docker/heat/.
    image: ttsubo/heat:queens
    command: /bin/sh -c "sleep 100; /root/init_queens.sh; /usr/bin/supervisord -n"
    container_name: heat-server
    hostname: heat-server
    volumes:
    - ./log:/log
    environment:
    - OS_PROJECT_DOMAIN_NAME=default
    - OS_USER_DOMAIN_NAME=default
    - OS_PROJECT_NAME=admin
    - OS_USERNAME=admin
    - OS_PASSWORD=passw0rd
    - OS_AUTH_URL=http://keystone-server:35357/v3
    - OS_IDENTITY_API_VERSION=3
    - OS_IMAGE_API_VERSION=2
    privileged: true
