apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance-pod
  labels:
    name: glance-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: glance-pod
  template:
    metadata:
      labels:
        name: glance-pod
    spec:
      containers:
      - name: glance-pod
        image: gcr.io/gke-sample-211005/glance:1.0.1
        ports:
        - containerPort: 9292
        env:
        - name: OS_PROJECT_DOMAIN_NAME
          value: "default"
        - name: OS_USER_DOMAIN_NAME
          value: "default"
        - name: OS_PROJECT_NAME
          value: "admin"
        - name: OS_USERNAME
          value: "admin"
        - name: OS_PASSWORD
          value: "passw0rd"
        - name: OS_AUTH_URL
          value: "http://keystone-server:35357/v3"
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_IMAGE_API_VERSION
          value: "2"
        command: ["/bin/sh"]
        args: ["-c", "sleep 60; /root/init_mitaka.sh; /usr/bin/supervisord -n"]
