apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neutron-pod
  labels:
    name: neutron-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: neutron-pod
    spec:
      containers:
      - name: neutron-pod
        image: gcr.io/gke-sample-180904/neutron:1.0.1
        ports:
        - containerPort: 9696
        securityContext:
          privileged: true
        env:
        - name: OS_PROJECT_DOMAIN_NAME
          value: "default"
        - name: OS_USER_DOMAIN_NAME
          value: "default"
        - name: OS_PROJECT_NAME
          value: "admin"
        - name: OS_USERNAME
          value: "admin"
        - name: OS_PASSWORD
          value: "passw0rd"
        - name: OS_AUTH_URL
          value: "http://keystone-server:35357/v3"
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_IMAGE_API_VERSION
          value: "2"
        command: ["/bin/sh"]
        args: ["-c", "sleep 80; /root/init_mitaka.sh; /usr/bin/supervisord -n"]
