apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-pod
  labels:
    name: nova-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nova-pod
  template:
    metadata:
      labels:
        name: nova-pod
    spec:
      containers:
      - name: nova-pod
        image: gcr.io/gke-sample-211005/nova:1.0.1
        ports:
        - containerPort: 5999
        - containerPort: 8773
        - containerPort: 8774
        - containerPort: 8775
        securityContext:
          privileged: true
        env:
        - name: OS_PROJECT_DOMAIN_NAME
          value: "default"
        - name: OS_USER_DOMAIN_NAME
          value: "default"
        - name: OS_PROJECT_NAME
          value: "admin"
        - name: OS_USERNAME
          value: "admin"
        - name: OS_PASSWORD
          value: "passw0rd"
        - name: OS_AUTH_URL
          value: "http://keystone-server:35357/v3"
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_IMAGE_API_VERSION
          value: "2"
        command: ["/bin/sh"]
        args: ["-c", "sleep 80; /root/init_mitaka.sh; /usr/bin/supervisord -n"]
