apiVersion: v1
kind: Service
metadata:
  labels:
    name: keystone-server
  name: keystone-server
spec:
  ports:
  - name: admin-port
    port: 35357
  - name: public-port
    port: 5000
  selector:
    name: keystone-pod
